/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VipRouteImport } from './routes/vip'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiWebhookRouteImport } from './routes/api/webhook'
import { Route as ApiRecommendationsRouteImport } from './routes/api/recommendations'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as ApiAnalyticsRouteImport } from './routes/api/analytics'
import { Route as ApiCronCrawlerRouteImport } from './routes/api/cron/crawler'

const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiWebhookRoute = ApiWebhookRouteImport.update({
  id: '/api/webhook',
  path: '/api/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecommendationsRoute = ApiRecommendationsRouteImport.update({
  id: '/api/recommendations',
  path: '/api/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsRoute = ApiAnalyticsRouteImport.update({
  id: '/api/analytics',
  path: '/api/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronCrawlerRoute = ApiCronCrawlerRouteImport.update({
  id: '/api/cron/crawler',
  path: '/api/cron/crawler',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/categorias': typeof CategoriasRoute
  '/favoritos': typeof FavoritosRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vip': typeof VipRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/recommendations': typeof ApiRecommendationsRoute
  '/api/webhook': typeof ApiWebhookRoute
  '/admin/': typeof AdminIndexRoute
  '/api/cron/crawler': typeof ApiCronCrawlerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categorias': typeof CategoriasRoute
  '/favoritos': typeof FavoritosRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vip': typeof VipRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/recommendations': typeof ApiRecommendationsRoute
  '/api/webhook': typeof ApiWebhookRoute
  '/admin': typeof AdminIndexRoute
  '/api/cron/crawler': typeof ApiCronCrawlerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/categorias': typeof CategoriasRoute
  '/favoritos': typeof FavoritosRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vip': typeof VipRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/recommendations': typeof ApiRecommendationsRoute
  '/api/webhook': typeof ApiWebhookRoute
  '/admin/': typeof AdminIndexRoute
  '/api/cron/crawler': typeof ApiCronCrawlerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/categorias'
    | '/favoritos'
    | '/onboarding'
    | '/perfil'
    | '/sitemap.xml'
    | '/vip'
    | '/api/analytics'
    | '/api/checkout'
    | '/api/recommendations'
    | '/api/webhook'
    | '/admin/'
    | '/api/cron/crawler'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/categorias'
    | '/favoritos'
    | '/onboarding'
    | '/perfil'
    | '/sitemap.xml'
    | '/vip'
    | '/api/analytics'
    | '/api/checkout'
    | '/api/recommendations'
    | '/api/webhook'
    | '/admin'
    | '/api/cron/crawler'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/categorias'
    | '/favoritos'
    | '/onboarding'
    | '/perfil'
    | '/sitemap.xml'
    | '/vip'
    | '/api/analytics'
    | '/api/checkout'
    | '/api/recommendations'
    | '/api/webhook'
    | '/admin/'
    | '/api/cron/crawler'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CategoriasRoute: typeof CategoriasRoute
  FavoritosRoute: typeof FavoritosRoute
  OnboardingRoute: typeof OnboardingRoute
  PerfilRoute: typeof PerfilRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VipRoute: typeof VipRoute
  ApiAnalyticsRoute: typeof ApiAnalyticsRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiRecommendationsRoute: typeof ApiRecommendationsRoute
  ApiWebhookRoute: typeof ApiWebhookRoute
  ApiCronCrawlerRoute: typeof ApiCronCrawlerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/webhook': {
      id: '/api/webhook'
      path: '/api/webhook'
      fullPath: '/api/webhook'
      preLoaderRoute: typeof ApiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recommendations': {
      id: '/api/recommendations'
      path: '/api/recommendations'
      fullPath: '/api/recommendations'
      preLoaderRoute: typeof ApiRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics': {
      id: '/api/analytics'
      path: '/api/analytics'
      fullPath: '/api/analytics'
      preLoaderRoute: typeof ApiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/crawler': {
      id: '/api/cron/crawler'
      path: '/api/cron/crawler'
      fullPath: '/api/cron/crawler'
      preLoaderRoute: typeof ApiCronCrawlerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CategoriasRoute: CategoriasRoute,
  FavoritosRoute: FavoritosRoute,
  OnboardingRoute: OnboardingRoute,
  PerfilRoute: PerfilRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VipRoute: VipRoute,
  ApiAnalyticsRoute: ApiAnalyticsRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiRecommendationsRoute: ApiRecommendationsRoute,
  ApiWebhookRoute: ApiWebhookRoute,
  ApiCronCrawlerRoute: ApiCronCrawlerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
